
Create dATABASE DUAN_1

CREATE TABLE NHANVIEN(
MANV NVARCHAR(50),
TENNV NVARCHAR(50),
DIACHI NVARCHAR(50),
SOGIOLAM INT,
SONGAYLAM INT,
NGAYSINH DATE,
SDT NVARCHAR(50),
LUONGPHAITRA FLOAT,
GIOITINH NVARCHAR(50),
VAITRO NVARCHAR(50),

)

CREATE TABLE NGUYENLIEU(
MANL NVARCHAR(50),
TENNL NVARCHAR(50),
SOLUONG INT,
GIATIEN FLOAT,
TRANGTHAI NVARCHAR(50),
MOTA NVARCHAR(50)
)

CREATE TABLE MENU(
MAMON NVARCHAR(50),
TENMON NVARCHAR(50),
SOLUONG INT,
GIATIEN FLOAT,
MOTA NVARCHAR(50)
)

CREATE TABLE KHUYENMAI(
MAKM NVARCHAR(50),
TENKM NVARCHAR(50),
TRANGTHAI NVARCHAR(50),
CHIETKHAU INT,
NOIDUNG NVARCHAR(100),
NGAYBATDAU DATE,
NGAYKETTHUC DATE
)

CREATE TABLE CALAM(
MANV NVARCHAR(50),
TENNV NVARCHAR(50),
CALAM NVARCHAR(50),

NGAYLAM DATE,
 
GIOVAOCA nvarchar(50),
GIOHETCA nvarchar(50),
TRANGTHAI INT 
)
 drop table calam

CREATE TABLE BANHANG(
TENKH NVARCHAR(50),
SOLUONGKHACH INT,
SDT NVARCHAR,
GIOVAOBAN DATETIME
)

CREATE TABLE HOADON(
MAHD NVARCHAR(50),
NGAYTAO DATE,
TRANGTHAI NVARCHAR(50),
THOIGIAN DATETIME ,
MAKM NVARCHAR(50) ,
MANV NVARCHAR(50) ,
THANHTIEN FLOAT 

)
CREATE TABLE BAN(
MABAN NVARCHAR(50),
TRANGTHAI INT 
)
CREATE TABLE TAIKHOAN (
  Ten NVARCHAR(50),
  Pass NVARCHAR(50),
  Role NVARCHAR(50)
) 
 
